### ISSUE TITLE
Shelikof Strait Ichthyoplankton, 1984-present (NOAA)

### ISSUE THREAD

**Issue by clward** [NCEAS/goa-data#15]
Contact: Dr. Janet Duffy-Anderson (NOAA)
Janet is preparing these data with Colette.  Goal is to have data ready for use at October 2015 meeting of the Portfolio Effects working group.  
Last contact: June 12, 2015.  Janet is probably at sea doing fieldwork for the summer.

**Comment by clward** [comment]
Emailed Janet Duffy-Anderson (NOAA) August 14, 2015 to enquire about getting this going again.

**Comment by reblake** [comment]
I believe this data were cleaned up and organized by Colette, and are currently being analyzed in the PFX working group.
