### ISSUE TITLE
Spawning habitat characteristics of pacific herring (Clupea pallasii) in Prince William Sound, Alaska

### ISSUE THREAD

**Issue by clward** [NCEAS/goa-data#23]
I think this is the reference:
Brandee L. Gerke. 2002. Spawning habitat characteristics of Pacific herring, Clupea pallasi, in Prince William Sound, Alaska. (Fisheries) University of Alaska Fairbanks, Juneau, Alaska. (M.S. Thesis)

This is the only study of herring spawning habitat conducted in Prince William Sound.  Thesis was not published and is not available online, also not available via UC Inter Library Loan.

https://data.doi.gov/dataset/spawning-habitat-characteristics-of-pacific-herring-clupea-pallasii-in-prince-william-soun

**Comment by reblake** [comment]
Jessica will make an inter-library load request (through UCSB library) for this MS thesis.

**Comment by reblake** [comment]
Have MS thesis in hand (ILL from UAF, Juneau) as of Aug 26th.  Due back to UCSB Sept 28th.  Will peruse and determine usefulness before that date.

**Comment by reblake** [comment]
I think we determined this wasn't useful.  Also, we are no longer pursuing this topic.
